Unsorting state update commit
loomnetwork/go-ethereum pull request #11
Opened 2019-11-05 04:53 UTC by pathornteng

This PR adds `GOETH_UNSORTING` environment variable to switch on/off sorting keys before updating and committing state.

2019-11-05 10:26 UTC, enlight requested changes

2019-11-05 10:26 UTC, enlight commented on core/state/state_object.go
> +var unsorting = (os.Getenv("GOETH_UNSORTING") == "true")
```golang
var EnableStateObjectDirtyStorageKeysSorting = true
```

2019-11-05 10:26 UTC, enlight commented on trie/database.go
> +	unsorting = (os.Getenv("GOETH_UNSORTING") == "true")
```golang
EnableTrieDatabasePreimageKeysSorting = true
```

2019-11-05 10:26 UTC, enlight commented on core/state/state_object.go
> +var unsorting = (os.Getenv("GOETH_UNSORTING") == "true")
Then you set it like this in loomchain on startup
```golang

// import "github.com/ethereum/go-ethereum/core/state"
state.EnableStateObjectDirtyStorageKeysSorting = false
```

2019-11-05 14:55 UTC, pathornteng commented on core/state/state_object.go
> +var unsorting = (os.Getenv("GOETH_UNSORTING") == "true")
Done

2019-11-05 14:55 UTC, pathornteng commented on trie/database.go
> +	unsorting = (os.Getenv("GOETH_UNSORTING") == "true")
Done

2019-11-22 08:39 UTC, enlight approved these changes
LGTM

2019-11-22 08:45 UTC, merged